// Generated by CoffeeScript 1.6.3
(function() {
  window.zipper = {};

  window.zipper.indexedDB = {};

  zipper.indexedDB.open = function(databaseName, operation) {
    var request;
    request = indexedDB.open(databaseName);
    request.onsuccess = function(e) {
      zipper.indexedDB.db = e.target.result;
      if ((operation != null) && typeof operation === 'function') {
        operation();
        return zipper.indexedDB.close();
      } else {
        return console.log('Database has been opened. Please remember to close it after use.');
      }
    };
    return request.onerror = zipper.indexedDB.onerror;
  };

  zipper.indexedDB.onerror = function(e) {
    return console.debug('ERROR', e);
  };

  zipper.indexedDB.close = function() {
    if (zipper.indexedDB.db) {
      return zipper.indexedDB.db.close();
    }
  };

  zipper.indexedDB.drop = function(databaseName) {
    return indexedDB.deleteDatabase(databaseName);
  };

  zipper.generateDownloadUrl = function(content) {
    var blob;
    blob = new Blob([content], {
      type: 'application/octet-binary'
    });
    return URL.createObjectURL(blob);
  };

  zipper.indexedDB.bootstrap = function() {
    var request, version;
    version = 1;
    request = indexedDB.open("zipper", version);
    request.onupgradeneeded = zipper.indexedDB.populate;
    return request.onerror = zipper.indexedDB.onerror;
  };

}).call(this);
