// Generated by CoffeeScript 1.6.3
(function() {
  zipper.download = function() {
    var dbOperation, rows;
    rows = [];
    dbOperation = function() {
      var cursorRequest, db, name, objectStoreNames, store, transaction, _i, _len, _results;
      db = zipper.indexedDB.db;
      objectStoreNames = db.objectStoreNames;
      transaction = db.transaction(objectStoreNames, 'readonly');
      _results = [];
      for (_i = 0, _len = objectStoreNames.length; _i < _len; _i++) {
        name = objectStoreNames[_i];
        store = transaction.objectStore(name);
        cursorRequest = store.openCursor();
        cursorRequest.onsuccess = function(e) {
          var content, result, tag, url;
          result = e.target.result;
          if (result != null) {
            rows.push(JSON.stringify(result.value));
            return result["continue"]();
          } else {
            content = rows.join("\n");
            url = zipper.generateDownloadUrl(content);
            tag = $('<a/>').attr('href', url).text('Download here');
            return $('body').append(tag);
          }
        };
        _results.push(cursorRequest.onerror = zipper.indexedDB.onerror);
      }
      return _results;
    };
    return zipper.indexedDB.open(dbOperation);
  };

}).call(this);
