// Generated by CoffeeScript 1.6.3
(function() {
  zipper.downloadStructure = function() {
    var dbOperation;
    dbOperation = function() {
      var databaseJson, db, index, indexJson, indexName, indexNames, name, objectStoreNames, store, storeJson, tag, transaction, url, _i, _j, _len, _len1;
      db = zipper.indexedDB.db;
      databaseJson = {};
      databaseJson.name = db.name;
      databaseJson.version = db.version;
      databaseJson.objectStores = [];
      objectStoreNames = db.objectStoreNames;
      transaction = db.transaction(objectStoreNames, 'readonly');
      for (_i = 0, _len = objectStoreNames.length; _i < _len; _i++) {
        name = objectStoreNames[_i];
        store = transaction.objectStore(name);
        storeJson = {};
        storeJson.name = store.name;
        storeJson.keyPath = store.keyPath;
        storeJson.options = {
          autoIncrement: store.autoIncrement
        };
        storeJson.indexes = [];
        indexNames = store.indexNames;
        for (_j = 0, _len1 = indexNames.length; _j < _len1; _j++) {
          indexName = indexNames[_j];
          index = store.index(indexName);
          indexJson = {};
          indexJson.name = indexName;
          indexJson.keyPath = index.keyPath;
          indexJson.options = {
            unique: index.unique,
            multiEntry: index.multiEntry
          };
          storeJson.indexes.push(indexJson);
        }
        databaseJson.objectStores.push(storeJson);
      }
      url = zipper.generateDownloadUrl(JSON.stringify(databaseJson));
      tag = $('<a/>').attr('href', url).text('Download here');
      return $('body').append(tag);
    };
    return zipper.indexedDB.open(dbOperation);
  };

}).call(this);
