// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    $('#create').on('click', zipper.indexedDB.populate);
    return $('#download').on('click', zipper.download);
  });

}).call(this);
