// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function() {
    $('#create').on('click', zipper.indexedDB.open);
    $('#download').on('click', zipper.backupStructure);
    $('#downloadBoth').on('click', zipper.backupStructureAndData);
    $('#drop').on('click', zipper.indexedDB.drop);
    return $('#restore').on('click', function() {
      var jsonString;
      jsonString = $('#json').val();
      return zipper.indexedDB.restore(jsonString);
    });
  });

}).call(this);
