// Generated by CoffeeScript 1.6.3
(function() {
  zipper.indexedDB.populate = function(e) {
    var db, leftStore, n, rightStore, _results;
    db = zipper.indexedDB.db = e.target.result;
    e.target.transaction.onerror = zipper.indexedDB.onerror;
    if (db.objectStoreNames.contains("left")) {
      db.deleteObjectStore("left");
    }
    leftStore = db.createObjectStore("left", {
      keyPath: "id",
      autoComplete: true
    });
    if (db.objectStoreNames.contains("right")) {
      db.deleteObjectStore("right");
    }
    rightStore = db.createObjectStore("right", {
      keyPath: "id",
      autoComplete: true
    });
    n = 10;
    _results = [];
    while (n -= 1) {
      leftStore.add({
        id: n,
        desc: "left #" + n
      });
      _results.push(rightStore.add({
        id: n,
        desc: "right #" + n
      }));
    }
    return _results;
  };

}).call(this);
