// Generated by CoffeeScript 1.6.3
(function() {
  zipper.indexedDB.print = function() {
    var dbOperation, renderRecord;
    renderRecord = function(record) {
      debugger;
      var row;
      row = $('<div/>').addClass('record').text(JSON.stringify(record));
      return $('.data').append(row);
    };
    dbOperation = function() {
      var cursorRequest, db, name, objectStoreNames, store, transaction, _i, _len, _results;
      db = zipper.indexedDB.db;
      objectStoreNames = db.objectStoreNames;
      transaction = db.transaction(objectStoreNames, 'readonly');
      _results = [];
      for (_i = 0, _len = objectStoreNames.length; _i < _len; _i++) {
        name = objectStoreNames[_i];
        store = transaction.objectStore(name);
        cursorRequest = store.openCursor();
        cursorRequest.onsuccess = function(e) {
          var result;
          result = e.target.result;
          if (result != null) {
            renderRecord(result.value);
            return result["continue"]();
          }
        };
        _results.push(cursorRequest.onerror = zipper.indexedDB.onerror);
      }
      return _results;
    };
    return zipper.indexedDB.open(dbOperation);
  };

}).call(this);
