// Generated by CoffeeScript 1.6.3
(function() {
  zipper.indexedDB.restore = function(jsonString) {
    var dbOperation;
    dbOperation = function() {
      var databaseJson, request;
      databaseJson = JSON.parse(jsonString);
      request = indexedDB.open(databaseJson.name, databaseJson.version, databaseJson.options);
      request.onupgradeneeded = function(e) {
        var db, indexJson, store, storeJson, _i, _len, _ref, _results;
        db = e.target.result;
        _ref = databaseJson.objectStores;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          storeJson = _ref[_i];
          store = db.createObjectStore(storeJson.name, storeJson.version, storeJson.options);
          _results.push((function() {
            var _j, _len1, _ref1, _results1;
            _ref1 = storeJson.indexes;
            _results1 = [];
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              indexJson = _ref1[_j];
              _results1.push(store.createIndex(indexJson.name, indexJson.keyPath, indexJson.options));
            }
            return _results1;
          })());
        }
        return _results;
      };
      request.onsuccess = function(e) {
        console.log("Database", databaseJson.name, "is already at version", databaseJson.version);
        return console.log("Nothing is done");
      };
      return request.onerror = zipper.indexedDB.error;
    };
    return zipper.indexedDB.open(dbOperation);
  };

}).call(this);
